# Generated by Django 3.2.8 on 2021-12-28 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='', max_length=160)),
                ('season', models.CharField(default='', max_length=160)),
                ('month', models.CharField(default='', max_length=160)),
                ('state', models.CharField(default='', max_length=160)),
                ('county', models.CharField(default='', max_length=160)),
                ('location', models.CharField(default='', max_length=160)),
                ('observed', models.CharField(default='', max_length=160)),
                ('notes', models.TextField(default='')),
                ('special_number', models.IntegerField(default='')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
