# Generated by Django 3.2.8 on 2021-12-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='observed',
            field=models.TextField(default=''),
        ),
    ]
