# Generated by Django 3.2.8 on 2021-12-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='title',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='county',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='location',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='month',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='observed',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='season',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='state',
            field=models.CharField(default='', max_length=160),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='year',
            field=models.CharField(default='', max_length=160),
        ),
    ]
