# Generated by Django 3.2.8 on 2021-12-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bookmark_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='notes',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='special_number',
            field=models.CharField(default='', max_length=160),
        ),
    ]
