# Generated by Django 3.2.8 on 2021-12-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211228_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalnotes',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
