# Generated by Django 3.2.8 on 2021-12-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_journalnotes_logged_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalNotes',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
